# Description: Docker Compose configuration file for the Avito Parser project.
name: avito-prices-full


# SERVICES ---------------------------------------------------------------------
services:
  # Parser
  parser:
    extends:
      file: minimal.compose.yml
      service: parser
    build:
      args:
        BASE_IMAGE_TAG: 3.13.1-bookworm
        PROJECT_EDITION: full
    command: [
      "python",
      "-m",
      "main",
      "search-on-avito-from-file",
      "../request-entries/example.yaml",
      "--max-pages",
      "5",
      "--min-price",
      "40",
      "--max-price",
      "10000",
      "--save-to-db",
    ]

    env_file:
      - ../.envs/.mongodb
    environment:
      MONGO_USERNAME_FILE: /run/secrets/mongo-username
      MONGO_PASSWORD_FILE: /run/secrets/mongo-password
    secrets:
      - mongo-username
      - mongo-password

    networks:
      - common

    depends_on:
      mongodb:
        condition: service_healthy


  # MongoDB service ------------------------------------------------------------
  mongodb:
    build:
      context: ..
      dockerfile: docker/dockerfiles/mongodb.Dockerfile
      args:
        BASE_IMAGE_TAG: 7.0.3-ubi9

    image: mongodb
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped

    privileged: false
    read_only: true
    tmpfs:
      - /tmp
    cpu_count: 1
    mem_reservation: "256m"
    mem_limit: "512m"
    memswap_limit: "1024m"
    pids_limit: 100
    security_opt:
      - "no-new-privileges=true"

    env_file:
      - ../.envs/.mongodb
    environment:
      MONGODB_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo-root-username
      MONGODB_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-password
      MONGO_USERNAME_FILE: /run/secrets/mongo-username
      MONGO_PASSWORD_FILE: /run/secrets/mongo-password
    secrets:
      - mongo-root-username
      - mongo-root-password
      - mongo-username
      - mongo-password

    volumes:
      - mongodb_data:/data/db:z

    networks:
      - common

    healthcheck:
      test: [ "CMD-SHELL", "/check-mongo" ]
      interval: 1m
      timeout: 15s
      retries: 5
      start_period: 1m


  # MongoExpress service -------------------------------------------------------
  mongoexpress:
    build:
      context: ..
      dockerfile: docker/dockerfiles/mongoexpress.Dockerfile
      args:
        BASE_IMAGE_TAG: 1.0.2-20-alpine3.19

    image: mongoexpress
    container_name: mongoexpress
    hostname: mongoexpress
    restart: unless-stopped

    privileged: false
    read_only: true
    cpu_count: 1
    mem_reservation: "128m"
    mem_limit: "256m"
    memswap_limit: "512m"
    pids_limit: 100
    security_opt:
      - "no-new-privileges=true"

    env_file:
      - ../.envs/.mongoexpress
    environment:
      ME_CONFIG_BASICAUTH_USERNAME_FILE: /run/secrets/mongoexpress-username
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/mongoexpress-password
      ME_CONFIG_MONGODB_ADMINUSERNAME_FILE: /run/secrets/mongo-root-username
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongo-root-password
    secrets:
      - mongoexpress-username
      - mongoexpress-password
      - mongo-root-username
      - mongo-root-password

    ports:
      - "8081:8081"

    networks:
      - common

    depends_on:
      mongodb:
        condition: service_healthy

    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://0.0.0.0:8081/status" ]
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 1m


# SECRETS -----------------------------------------------------------------------
secrets:
  mongo-root-username:
    file: ../.secrets/.mongo-root-username
  mongo-root-password:
    file: ../.secrets/.mongo-root-password
  mongo-username:
    file: ../.secrets/.mongo-username
  mongo-password:
    file: ../.secrets/.mongo-password
  mongoexpress-username:
    file: ../.secrets/.mongoexpress-username
  mongoexpress-password:
    file: ../.secrets/.mongoexpress-password


# VOLUMES -----------------------------------------------------------------------
volumes:
  mongodb_data: {}


# NETWORKS ----------------------------------------------------------------------
networks:
  common:
    name: avito-parser-net
    driver: bridge
    external: false
