#!/bin/bash

set -e
set -o pipefail
set -o nounset

# -----------------------------------------------------------------------------

ping_result=$(echo 'db.runCommand("ping").ok' | mongosh localhost:$MONGO_PORT/test --quiet 2>&1 | grep -o '[0-9]\+')

if [ "$ping_result" -eq 1 ]; then
  echo "MongoDB is healthy!"
  exit 0
else
  echo "MongoDB is unhealthy!"
  echo "Error: $ping_result"
  exit 1
fi
